### ISSUE TITLE
知乎的知乎专栏  entry-title-image 的img请设置100%宽度

### ISSUE THREAD

**Issue by DemonCloud** [Frizen/Plains-Gate#11]
```
.post-view .entry-title-image img{
     display: block;
     with: 100%;
     zoom: 1;
}
```

如果上传图片不是你定义的宽度，则title img 显示为原始窄宽， 见图

![2016-06-16_173613](https://cloud.githubusercontent.com/assets/7436361/16112212/f16f9302-33e8-11e6-8c93-0ed0c12a2001.png)

**Comment by Frizen** [comment]
知乎原生的 css 里已经给了 width:100%

```
.post-view .entry-title-image .img {
    width: 100%;
    height: 100%;
    background-size: cover;
    background-position: center;
}
```

但是你这个问题比较奇怪，我刚刚尝试上传同一张图片（600*450，png）到专栏，没有重现到你的那个情况…
