### ISSUE TITLE
和夜间模式样式的兼容性问题

### ISSUE THREAD

**Issue by gloomy-ghost** [Frizen/Plains-Gate#13]
更新之后`.top-nav-profile .zu-top-nav-userinfo`被强制设置了`background: #137AD5`， 如果同时开启[夜间模式](https://userstyles.org/styles/124816/dark-zhihu-v0-4-beta)的话用户栏仍然会保持蓝色：
![image](https://cloud.githubusercontent.com/assets/13086421/17502222/3972a506-5e3a-11e6-8144-aff8c2a70686.png)

注释掉颜色之后的效果：
![image](https://cloud.githubusercontent.com/assets/13086421/17502250/80416878-5e3a-11e6-9972-b5a22bdffde7.png)
而且不影响鼠标移动到用户栏后自动展开变色：
![image](https://cloud.githubusercontent.com/assets/13086421/17502279/b87f0cc2-5e3a-11e6-925d-e5bde148e22b.png)

另外现在github上的代码好像还没有同步更新？

**Comment by Frizen** [comment]
所以解决方法就是最好不要跟其他 styles 共用…因为这个 css 里面用了很多 !important 的语句，所以我只能保证 flat_zhihu 在独立使用的情况下尽量不出 bug，但有其他 style 介入的话就无法保证了。
