### ISSUE TITLE
顶部搜索栏错位了

### ISSUE THREAD

**Issue by Removable** [Frizen/Plains-Gate#14]
如题，浏览器是Chrome 53.x，分辨率是1600*900，系统win7
![image](https://cloud.githubusercontent.com/assets/7271713/19211084/cb2e1a56-8d66-11e6-913b-ed95b812a1c5.png)

**Comment by Frizen** [comment]
这个截图很明显你还没有开 flat_zhihu 啊…

**Comment by Removable** [comment]
可是stylish上面的flat_zhihu已经打勾了啊，其他网站的脚本都正常运行了

**Comment by Frizen** [comment]
可能是下载的时候出错了之类的原因吧。你可以对比一下 github 里面的代码看一下是不是少了一部分

**Comment by Removable** [comment]
我把github里面的css代码复制到stylish里面也还是没起作用。。。

**Comment by Frizen** [comment]
github 里的代码不能直接复制的。要用 stylish 的导入功能

**Comment by Removable** [comment]
是那个导入Mozilla 格式吗？

**Comment by laxect** [comment]
https://userstyles.org/styles/108011/flat-zhihu-v2-3-2
你得在这个页面安装啊…

**Comment by Jamesits** [comment]
2.3.2 的确有这个问题，我在 WIndows 10 / ChromeOS 下均能复现。2.3.1 工作正常。
怀疑是上传时候出了错。

**Comment by Removable** [comment]
我在那装了也不行啊，所以我才想到复制的

laxect notifications@github.com于2016年10月8日周六 20:06写道：

**Comment by Jamesits** [comment]
直接把 2.3.1 导入进来是可以用的……不过我 macOS 上不知为何 2.3.1 没法自动更新到 2.3.2 了

**Comment by Removable** [comment]
唉算了，其他样式都OK，就这个不行。就不折腾了，老老实实用客户端

James Swineson notifications@github.com于2016年10月9日周日 10:05写道：

**Comment by Jamesits** [comment]
手持 ChromeOS 表示客户端是啥……

**Comment by Removable** [comment]
😂起码比WP好

James Swineson notifications@github.com于2016年10月9日周日 10:09写道：

**Comment by Jamesits** [comment]
默默掏出我的 WP 看了一眼……

**Comment by Removable** [comment]
😂当我没说

James Swineson notifications@github.com于2016年10月9日周日 10:21写道：

**Comment by miyuchina** [comment]
刚才从 Stylish 网站更新了最新版本，能够重现问题。macOS 10.12, Chrome 53.0.2785.143.

检查了一下发现 `zu-top-search-input` 上面多了一个元素 `<label for="q" class="hide-text">知乎搜索</label>` ，如果把这个元素写成 `display: none;` 的话就可以恢复搜索栏位置...

但是貌似 `margin` 还需要微调一下，没有完全居中。

**Comment by Frizen** [comment]
大半夜登上来 github 看到一堆 notification 实在是超暖心的，虽然两天前就知道有这个 issue 了但是最近工作太忙了一直抽不出时间，明天会抽时间去看一下代码的。

感谢大家的关注 >。<

**Comment by FakeFranco** [comment]
我也是这个问题~

**Comment by Frizen** [comment]
> 刚才从 Stylish 网站更新了最新版本，能够重现问题。macOS 10.12, Chrome 53.0.2785.143.
> 
> 检查了一下发现 zu-top-search-input 上面多了一个元素 <label for="q" class="hide-text">知乎搜索</label> ，如果把这个元素写成 display: none; 的话就可以恢复搜索栏位置...
> 
> 但是貌似 margin 还需要微调一下，没有完全居中。

@qq576053126 @miyuchina @FrancoWay 
我刚刚重新检查了一下代码，确实代码里面有写针对 hide-text 这个元素的 display: none;  啊...
而且重新在 stylish 上下载了脚本，也有这行代码啊，为什么你们会出现这个问题呢…真是奇怪了…

**Comment by Foair** [comment]
现在我重新下了一遍，好像已经好了。感谢作者。

**Comment by FakeFranco** [comment]
@Frizen 刚重新在userstyles.org下载了下，没问题了~ 哈哈，很完美哦

**Comment by Removable** [comment]
的确，好像可以了

Weifffffff notifications@github.com于2016年10月13日周四 下午2:28写道：
