### ISSUE TITLE
考虑屏蔽广告？

### ISSUE THREAD

**Issue by tatamu-fold** [Frizen/Plains-Gate#18]
可以考虑加入.Banner {display:none}来屏蔽问题页广告？

**Comment by Frizen** [comment]
感谢建议。

其实在很早之前就有人建议过可以加入屏蔽广告功能了，技术上也十分容易实现，但是最后并没有彻底地屏蔽，而是通过降低透明度来减少广告的存在感——这当然存在一些客观因素的影响，因为直接屏蔽的话会让我的立场变得有点微妙——但更重要的是，无论作为一个互联网工作者也好，还是作为一个知乎的老用户也好，我并不认为「以营利目的在网站里加入广告」是可耻的，相反，这应该是光明正大理所当然的事情。当然，前提是这些广告不会大幅度的降低用户体验——在这一点上，我认为知乎做得已经足够克制了（都是同行衬托得好），因此我也只是在这基础上，以个人的感觉和判断加以优化一下。

如果你觉得有需要屏蔽广告，我建议你自己额外多写一个 style 来实现（当然也可以直接加入到 flat_zhihu 里面，但是这样一旦更新就会被 overwrite 了）。

再次感谢。

**Comment by tatamu-fold** [comment]
非常感谢您的回复！就是因为每次更新都会 overwrite ，所以不如考虑一下在安装页面上提供选项，默认不屏蔽，但可选屏蔽。但我不知道这样子更新能不能保持这个配置。
谢谢！
