### ISSUE TITLE
能否在 README 里加一个「User Guide」？

### ISSUE THREAD

**Issue by mzlogin** [Frizen/Plains-Gate#2]
我是从知乎页面 http://www.zhihu.com/question/37146954#answer-23712724 看到的这个项目并顺着里面贴的知乎专栏链接找到使用方法，感觉挺好用的，不过如果首先看到的是这个仓库，那像我这种不了解相关工具和用法的人，可能会产生困惑。

感谢你的相关工作！

**Comment by Frizen** [comment]
Done.

**Comment by Frizen** [comment]
Thx for ur advice.

**Comment by mzlogin** [comment]
Nice, so efficient~
