### ISSUE TITLE
查看对话右上角的关闭按钮不见了

### ISSUE THREAD

**Issue by laxect** [Frizen/Plains-Gate#7]
RT
[截图](https://drive.google.com/file/d/0BzgW9bAhZq3sOTUtV1dveFNCLUk/view)

**Comment by Frizen** [comment]
然而我这边能看到 -..-
[https://drive.google.com/file/d/0B3A5DDIjvMKtcTFBQWdEOElkLVU/view](url)

**Comment by laxect** [comment]
不知为何我这也有了=.=
